Proper stderr output.

diff --git a/src/mmt-isabelle/etc/settings b/src/mmt-isabelle/etc/settings
--- a/src/mmt-isabelle/etc/settings
+++ b/src/mmt-isabelle/etc/settings
@@ -10,5 +10,5 @@ then
   classpath "$ISABELLE_MMT_ROOT/deploy/mmt.jar"
   isabelle_scala_service "info.kwarc.mmt.isabelle.Tools"
 else
-  echo "### Missing $ISABELLE_MMT_ROOT/deploy/mmt.jar"
+  echo >&2 "### Missing $ISABELLE_MMT_ROOT/deploy/mmt.jar"
 fi
